### ISSUE TITLE
Add the ability to run the application as a Docker container

### ISSUE THREAD

**Issue by gmolaire** [ornicar/lila-ws#107]
The only way to run the whole stack at the moment is by running everything on a host(s) or by isolating each piece using [lichocker](https://github.com/BrandonE/lichocker).

Unfortunately, [lichocker](https://github.com/BrandonE/lichocker) is running all processes in one container where most are in the background. This does not make real usage of a container as its scope is not limited to one process. Moreover, we end up with a container that acts the same way as if we were running all on the host machine.

### Proposal
Starting with this issue, my suggesting is clear: "**Dockerize**" each source application individually and build a real docker stack in [lichocker](https://github.com/BrandonE/lichocker) using docker-compose.

Furthermore, this container approach can re reused later to ease off the deployment methods and costs in the cloud.

### Usage examples

_Building the application will be as follow:_
`docker build -t lila-ws .`

_Running the application could be as follow:_
`docker run -it lila-ws`

_Running the application by overriding the properties would be as follow:_
`docker run -it -v $PWD:/usr/app -w /usr/app -e JAVA_OPTS="-Dproperty.key=value -Dother.property.key=other.value" lila-ws`

I can take care of it. It would be very useful for newcomers as myself!

**Comment by ornicar** [comment]
Lichess doesn't need it, so I'd prefer if docker integrations were maintained in a separate repo of yours.
