### ISSUE TITLE
broken by "Update netty-codec-http, netty-handler, ... to 4.1.53.Final"

### ISSUE THREAD

**Issue by niklasf** [ornicar/lila-ws#134]
Broken, as in not accepting WebSocket connections.

Bisected to https://github.com/ornicar/lila-ws/compare/8211bacc9ba3d12b0562c292cdb6ca9d66331c08...29e1d27656b7a46bf89dfe1f6f40b36b6e4fbe60

**Comment by ornicar** [comment]
can reproduce

**Comment by ornicar** [comment]
probably due to https://github.com/netty/netty/commit/d01471917b94d15fbe8b3b2e0f0ed8f24ee2954a#diff-ad77c33ff1cf244104f4b35353bd4363be784da284b6545e2909b12731e32702
