### ISSUE TITLE
websocket is closing or close state error on https://play.thechesslabs.com/bn8yBK6r

### ISSUE THREAD

**Issue by ravijatwa** [ornicar/lila-ws#161]
ebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
RoundController.actualSendMove @ round.js:5703
RoundController.sendMove @ round.js:5724
RoundController.onUserMove @ round.js:5584
(anonymous) @ round.js:2185
setTimeout (async)
callUserFunction @ round.js:2185
userMove @ round.js:2336
selectSquare @ round.js:2380
(anonymous) @ round.js:2870
animate @ round.js:2725
anim @ round.js:2641
start @ round.js:2870
(anonymous) @ round.js:3600
site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:530
setTimeout (async)
StrongSocket.send @ site.js:530
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
10site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
2site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:530
setTimeout (async)
StrongSocket.send @ site.js:530
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
4site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
round.js:140 POST https://play.thechesslabs.com/statlog?e=roundTransientExpire 404 (Not Found)
exports.text @ round.js:140
TransientMove.expire @ round.js:5193
setTimeout (async)
TransientMove.register @ round.js:5186
RoundController.actualSendMove @ round.js:5707
RoundController.sendMove @ round.js:5724
RoundController.onUserMove @ round.js:5584
(anonymous) @ round.js:2185
setTimeout (async)
callUserFunction @ round.js:2185
userMove @ round.js:2336
selectSquare @ round.js:2380
(anonymous) @ round.js:2870
animate @ round.js:2725
anim @ round.js:2641
start @ round.js:2870
(anonymous) @ round.js:3600
bn8yBK6r:1 Uncaught (in promise) Not Found
Promise.then (async)
exports.text @ round.js:140
TransientMove.expire @ round.js:5193
setTimeout (async)
TransientMove.register @ round.js:5186
RoundController.actualSendMove @ round.js:5707
RoundController.sendMove @ round.js:5724
RoundController.onUserMove @ round.js:5584
(anonymous) @ round.js:2185
setTimeout (async)
callUserFunction @ round.js:2185
userMove @ round.js:2336
selectSquare @ round.js:2380
(anonymous) @ round.js:2870
animate @ round.js:2725
anim @ round.js:2641
start @ round.js:2870
(anonymous) @ round.js:3600
22site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
2site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:530
setTimeout (async)
StrongSocket.send @ site.js:530
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
28site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
2site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:530
setTimeout (async)
StrongSocket.send @ site.js:530
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
4site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
2site.js:524 WebSocket is already in CLOSING or CLOSED state.
StrongSocket.send @ site.js:524
(anonymous) @ site.js:530
setTimeout (async)
StrongSocket.send @ site.js:530
(anonymous) @ site.js:446
(anonymous) @ site.js:695
Ackable.resend @ site.js:693
4site.js:524 WebSocket is already in CLOSING or CLOSED state.

**Comment by ravijatwa** [comment]
@ornicar please check why this is happening ?

**Comment by niklasf** [comment]
See response in Discord.

**Comment by vincent-schirmann** [comment]
Hi @ravijatwa , did you find any solution for your issue?

**Comment by minecraft8997** [comment]
Having exactly the same issue.
