### ISSUE TITLE
Version conflicts in library dependencies

### ISSUE THREAD

**Issue by fuscati** [ornicar/lila-ws#210]
When running ```sbt run``` I am getting version conflicts in library dependencies.

OS: Ubuntu 18.04
sbt: 1.4.9

Error:
```
java.lang.RuntimeException: found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error] 
[error] 	* org.scala-lang.modules:scala-java8-compat_2.13:1.0.0 (early-semver) is selected over 0.9.0
[error] 	    +- com.github.blemale:scaffeine_2.13:4.1.0            (depends on 1.0.0)
[error] 	    +- com.typesafe.akka:akka-actor_2.13:2.6.15           (depends on 0.9.0)
```

**Comment by milesbright** [comment]
I confirmed this on my system, I think we are both on this commit 483a7263aa1065484cf73263a49f3b679ac074d4

Some discussion on #how-to-setup-lila discord

OS: Ubuntu 20.10
JDK 11
sbt: 1.4.9

**Comment by niklasf** [comment]
No longer broken on latest master, right?

**Comment by fuscati** [comment]
RIght. All good now
